import Head from 'next/head'
import { 
  Box, 
  Center,
  Container,
  Flex, 
  Spacer,
  Grid, 
  GridItem,
  useColorModeValue,
  useDisclosure,
  Icon,
  Collapse
} from "@chakra-ui/react"

import {
  MdKeyboardArrowRight,
  HiCode
} from "@chakra-ui/react"

const NavItem = (props) => {
  const { icon, children, ...rest } = props;
  return (
    <Flex
      align="center"
      px="4"
      pl="4"
      py="3"
      cursor="pointer"
      color={useColorModeValue("inherit", "gray.400")}
      _hover={{
        bg: useColorModeValue("gray.100", "gray.900"),
        color: useColorModeValue("gray.900", "gray.200"),
      }}
      role="group"
      fontWeight="semibold"
      transition=".15s ease"
      {...rest}
    >
      {icon && (
        <Icon
          mr="2"
          boxSize="4"
          _groupHover={{
            color: useColorModeValue("gray.600", "gray.300"),
          }}
          as={icon}
        />
      )}
      {children}
    </Flex>
  );
};


export default function Navbar() {
  const integrations = useDisclosure();
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>      
      <NavItem icon={HiCode} onClick={integrations.onToggle}>
        Integrations
        <Icon
          as={MdKeyboardArrowRight}
          ml="auto"
          transform={integrations.isOpen && "rotate(90deg)"}
        />
      </NavItem>
      <Collapse in={integrations.isOpen} animateOpacity>
        <NavItem pl="8" py="2">
          Shopify
        </NavItem>
        <NavItem pl="8" py="2">
          Slack
        </NavItem>
        <NavItem pl="8" py="2">
          Zapier
        </NavItem>
        <NavItem pl="8" py="2">
          Bujang
        </NavItem>
      </Collapse>
    </div>
  )
}
